### ISSUE TITLE
download() method example in quickstart.rst

### ISSUE THREAD

**Issue by jackDiGi** [sbg/sevenbridges-python#10]
You have from version 0.2.0

> # Download a file to the current working directory
> new_file.download(wait=True)

should be something like

> new_file.download(path=new_file.name)

**Comment by damirkrstanovic** [comment]
This is a confirmed bug in the docs. Download method needs local filename (optionally with path), while all other parameters are optional, with `wait` parameter set to `True` by default.

**Comment by SenadI** [comment]
Fixed in 0.4.1. Remember to clear the cache on readthedocs page to see updates
