### ISSUE TITLE
Possible to have a wait for method for tasks?

### ISSUE THREAD

**Issue by zymergen-mbarton** [sbg/sevenbridges-python#110]
I have a small feature request. If it does not exist already, would it be
possible to have a method or function to wait for a task to complete? Currently
we're doing this by regularly polling the task status, but if there was a
native method supported by SBG, I think this would be helpful.

Thank you

**Comment by christiansbg** [comment]
Hi Michael, thanks for your feedback. Do you have in mind a simple wait() function that blocks until given task(s) finished execution, or a more sophisticated event notification system where you want to register a callback function that gets pinged upon task completion? Currently we have neither but are thinking about both, so your feedback would be helpful for internal prioritization.

**Comment by zymergen-mbarton** [comment]
I think a simple function that blocks until the task is done? The latter
sounds useful but I don't have much experience with aync etc. in python to
comment I think.

**Comment by QuicksilverMachine** [comment]
There is now a wait method for tasks in version 0.18.3](https://github.com/sbg/sevenbridges-python/releases/tag/0.18.3). It is a blocking function and can be provided a waiting period (default 10s) and a callback function along with it's arguments.
