### ISSUE TITLE
Large number of file queries generates a `sevenbridges.errors.SbgError: The Seven Bridges Platform is currently under maintenance` error.

### ISSUE THREAD

**Issue by zymergen-mbarton** [sbg/sevenbridges-python#112]
I'm currently querying a large number of files by name, which generates an
`sevenbridges.errors.SbgError` indicating the site is under maintanence. This
was produced outside of the maintanence window (6:30 PST) which I believe was
4.5 hours earlier today.

The logging output is listing the query produced as follows:

```
urllib3.connectionpool:https://api.sbgenomics.com:443 "GET /v2/files?fields=_all&project=zymergen%2Fproject-name&name=file_1&name=file_2..."
```

The python code is:

``` python
config.api.files.query(names=[...], project=...)
```

Is there a limit on the number of files that can be queried at once? I'm
currently trying to get a corresponding File object from an Import object so I
can move the file to a folder on SBG. Is there any easier way to do this than
querying by the Import destination name as a file query?

**Comment by zymergen-mbarton** [comment]
Example code:

```python
    for chunk in funcy.chunks(10, import_records):
        imported_files = config.api.files.query(
            names=[x.destination.name for x in chunk],
            project=config.project)
        for imported_file in imported_files:
            imported_file.move_to_folder(run_directory)
```

**Comment by QuicksilverMachine** [comment]
Sorry for the late response, since the query is a GET request all passed names were appended to the url as parameters, which can result in a 3000+ character long url. This in turn can cause issues on the backend. Unfortunately, this is a limitation of the query being a GET request. The library should raise a warning when the url is too large though, I will see about adding this with one of the next releases.

**Comment by zymergen-mbarton** [comment]
Thank you. A warning on the URL length would be useful.
I think being able to import files from a volume directly into a folder would be useful too, since the aim of this code was to move each of these files from the project root to a folder after import.

**Comment by QuicksilverMachine** [comment]
Version [0.18.3](https://github.com/sbg/sevenbridges-python/releases/tag/0.18.3) is now released and it adds a warning when the url is too large and prevents the request from being called at all.
