### ISSUE TITLE
When querying for files in a project by tag, are files in a sub folder returned?

### ISSUE THREAD

**Issue by zymergen-mbarton** [sbg/sevenbridges-python#114]
Does using `self.api.files.query(project=..., tags=[...])` return all the
tagged files that in a sub folder? For example if the files are tagged but
their location is under a folder in the project, but they have the passed tag,
are they returned? I believe the current behaviour in the python API returns a
`<Collection: total=0, available=0>`.

**Comment by christiansbg** [comment]
Unfortunately cross-folder search is currently not possible via the API. You would have to identify the folder first and provide it as `parent` argument in your tag search.

Example:
```python
folder = api.files.query(project="division/project", names=["myfolder"])[0]
tagged_files = api.files.query(parent=folder, tags=["tag1", "tag2"], limit=100).all()
```
