### ISSUE TITLE
problem on SBG aligner.

### ISSUE THREAD

**Issue by a00101** [sbg/sevenbridges-python#121]
Dear SBG developers.

first of all, plz forgive me jumping the fence.
Unfortunately, I don't know what exactly the place is to ask a question.
you had better to move right place, it's okay.

My problem is.
I download graph_genome.tar.gz and install docker images (BPA, RASM).
But packages contains just population vcf file(SBG.Graph.B37.V6.rc6.vcf.gz) based on B37 reference genome. Want to use GRCh38(hg38).
Could you tell me how to make reference GRCh38 or Could you just hand out GRCh38 file for me?

Thanks.

**Comment by perica22** [comment]
Hi @a00101, could you please submit your question on  support@sevenbridges.com, since this one is not as much related to sevenbridges-python library? Thank you
