### ISSUE TITLE
Connection dropped during rate_limit when behind proxy

### ISSUE THREAD

**Issue by golharam** [sbg/sevenbridges-python#122]
FYI - For the longest time, anytime my connection was rate limited and I was running behind our corporate proxy, the retry mechanism didn't work.  The connection was always dropped during retry.  It looks like v1.0.6 fixes this.  The connection gets re-established after rate-limiting while behind our proxy.

**Comment by golharam** [comment]
Actually, just encountered:

sevenbridges.errors.SbgError: HTTPSConnectionPool(host='api.sbgenomics.com', port=443): Max retries exceeded with url: /v2/files/asdfasdfq34523452345/list?fields=_all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111b3bb10>: Failed to establish a new connection: [Errno 60] Operation timed out'))

**Comment by QuicksilverMachine** [comment]
Hello @golharam , could you check with `pip freeze` which version do you have installed? The logs you've posted seem to be for version 1.0.5.
