### ISSUE TITLE
Error while uploading file - Upload not in PREPARING state

### ISSUE THREAD

**Issue by jackDiGi** [sbg/sevenbridges-python#13]
I tried the async uploader and got this message - not sure what it is about.

![image](https://cloud.githubusercontent.com/assets/13199814/17291955/2a12dc1a-57e7-11e6-810e-3f24832aaf4a.png)

**Comment by jackDiGi** [comment]
Upload(ing) file doesn't show up in the project, even though the upload.status is "RUNNING". Size is about 200 mb. Had let it sit about 10 mins. Then clear it out.

**Comment by damirkrstanovic** [comment]
@jackDiGi  - I am unable to reproduce this behavior, but with Python 2.7.10 I get the following error:
```
Traceback (most recent call last):
  File "/Users/damirk/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/damirk/miniconda2/lib/python2.7/site-packages/sevenbridges/transfer/upload.py", line 533, in run
    raise SbgError(six.text_type(e))
SbgError: 'Progress' object has no attribute 'num_of_chunks'
```

With Python 3.x I was unable to reproduce, nor with Python 2.7.12 from miniconda distribution.

Is this the full Anaconda distribution that you are using ?

**Comment by jackDiGi** [comment]
jupyter --version
4.0.6
python -V
Python 2.7.11 :: Anaconda 2.4.0 (x86_64)

**Comment by SenadI** [comment]
@jackDiGi 
I can confirm the issue. Will find out what is happening - fix it, comment it and release new version.

**Comment by mattions** [comment]
@Jack: do a `conda env export > enviroment.yml` so it will show all the
reqs, and there is a better chance to replicate the enviroment (
http://conda.pydata.org/docs/using/envs.html#export-the-environment-file)

**Comment by SenadI** [comment]
Hi @jackDiGi I can not reproduce this issue with valid conda setup.
