### ISSUE TITLE
Resource .get accepts empty strings

### ISSUE THREAD

**Issue by OgnjenMilicevic** [sbg/sevenbridges-python#17]
Library silently fails on api.tasks.get(''), it should throw an exception. The id of the resource being fetched should be validated before retrieval.

**Comment by damirkrstanovic** [comment]
Hey @OgnjenMilicevic  - this is interesting - where did you run into such a case ? Can you please describe it more.

**Comment by OgnjenMilicevic** [comment]
Support team ran into an error when reading a file with trailing new lines. This error will not be repeated, but it is not difficult to run into this case.

**Comment by damirkrstanovic** [comment]
Thanks @OgnjenMilicevic

**Comment by SenadI** [comment]
Fixed in v0.4.3
