### ISSUE TITLE
Get old app revisions

### ISSUE THREAD

**Issue by jdagilliland** [sbg/sevenbridges-python#18]
Retrieving non-current revisions of apps through the API is a challenge because the app IDs attached to the app objects include the number of the latest revision.
This means that when using the `App.get_revision()` function, it tries to append the desired revision number on to the current revision number (resulting in an invalid request).
I'm not quite sure how to fix this, because the instances of App that are retrieved through `api.apps.query()` already come with the revision number attached, but I imagine it would not be too hard for someone who knows the ins and outs of your API wrapper, because the return values of `list-all-apps-available-to-you` do not include revision numbers.

**Comment by jdagilliland** [comment]
Actually, it looks like it is in fact the documentation for `list-all-apps-available-to-you` which is wrong. Since the IDs returned by that call include the latest revision number, that would have to be stripped to provide a revision agnostic app ID.

**Comment by SenadI** [comment]
Fixed in v0.4.3

**Comment by jdagilliland** [comment]
Awesome, thx!
