### ISSUE TITLE
upload function shuold return the file identifier

### ISSUE THREAD

**Issue by mattions** [sbg/sevenbridges-python#21]
Right now the upload function does not return the file identifier, so a user does not have the ability to update the metadata just right off it.

Right now it looks like:
```
api.files.upload(name, to_project)
file_uploaded_identifier = self.to_platform.files.query(to_project, names=[name])[0]
# File operation
```

Would be nicer to have somenthig like:
```
file_uploaded_identifier = api.files.upload(name, to_project)
# file operation here for example metadata
```

**Comment by SenadI** [comment]
This is a valid request will be available in the upcoming version.

**Comment by SenadI** [comment]
Fixed in v.0.4.4
The syntax is 
```python
upload = api.files.upload(path, project, wait=True|False)
...
upload.result()
```
