### ISSUE TITLE
User surprise: Asking for file metadata via dot (.) operator overwrites name changes that have not been saved

### ISSUE THREAD

**Issue by kghosesbg** [sbg/sevenbridges-python#22]
Fetch a file
`f=api.files.get(id='57574236e4b083c873cc5eba')`

Check name

`f.name`
`Out[191]: u'haha.i.changed.this'`

Check metadata (I believe this fetches the metadata from the platform. I like it's lazy nature!)

`f.metadata`
``  (There's no metadata)

Change file name
`f.name = 'oops.i.changed.it.again'`
 
Verify the local version has the changed file name
`f.name`
`'oops.i.changed.it.again'`

Now ask to see the metadata again. What I did not expect was that a) this would be a fresh fetch of the metadata and, b) this would overwrite the file name

`f.metadata`
`` (No metadata as expected)

`f.name`
`'haha.i.changed.this'` <---- Zowie! Was not expecting this

Need to do `f.save()` first

**Comment by SenadI** [comment]
I can confirm this. Happens when the field that is re-fetched is None. I will fix this asap.

**Comment by SenadI** [comment]
Fixed in v0.4.4

**Comment by jackDiGi** [comment]
oops.i.changed.it.again for the win @kghosesbg

**Comment by kghosesbg** [comment]
@jackDiGi 's just relieved he's no longer the one I'm detaining at the office just before they were going home. This time it's @SenadI who had to spend an hour on Friday scrolling through my atrocious nonsense.

**Comment by kghosesbg** [comment]
#23
