### ISSUE TITLE
api.files.copy should copy a supplied file to destination

### ISSUE THREAD

**Issue by kghosesbg** [sbg/sevenbridges-python#25]
The current operation and help for the class function `api.files.copy` is:

```
api.files.copy?
Signature: api.files.copy(self, project, name=None)
Docstring:
Copies the current file.
:param project: Destination project.
:param name: Destination file name.
:return: Copied File object.
```

This is expected for a `file.copy` method of a `file` object, but I expect  `api.files.copy` to be a generalized copy function, taking a source file and a destination project with possibly a new name, all explicitly supplied to the function. The current function and help are ambiguous and unexpected.

Thanks!

**Comment by SenadI** [comment]
Hi @kghosesbg ,
The copy should be use only on file instances. We will no be adding this to the library.

**Comment by jackDiGi** [comment]
This maybe worth brief documentation somewhere, users may initially try to use methods **api.files.(copy, get)** in the same way they use **api.files.query** but they are _fundamentally different_. Same applies to projects, tasks, etc. Not sure the best way to tackle this from a user education perspective.

**Comment by kghosesbg** [comment]
Yes, I think these methods should be removed from `files`, `projects` etc. and only accessible through individual `file`, `project` ... objects.
