### ISSUE TITLE
VOLUMES error on non-hosted files, please make more actionable

### ISSUE THREAD

**Issue by jackDiGi** [sbg/sevenbridges-python#27]
User flow
- make a project "my-project"
- copy a Public Reference file to "my-project"
- try to export one of those files with
```
for f in selected_files:
    export = api.exports.submit_export(
        file=f,                        
        volume=my_volume,                     
        location=f.name) 
```
I get the error
> Forbidden: Requested file cannot be exported. Check the documentation.

But I don't have a link to "the documentation" so I don't know where to look. I don't see this mentioned in readthedocs and don't recall it on docs.sevenbridges.com either.

**Comment by damirkrstanovic** [comment]
Hi @jackDiGi, this is not related to library, but API messaging in general. Will close this one and take it in-house.

**Comment by jackDiGi** [comment]
thanks!
