### ISSUE TITLE
api.get_exports(project=my_project), not restricted to project

### ISSUE THREAD

**Issue by jackDiGi** [sbg/sevenbridges-python#28]
# Issue
I used:

```
all_export_jobs = my_volume.get_exports(project=my_project)

for j in all_export_jobs:
    print('File {} export is {}'
         .format(j.destination, j.state))
print('\n')
```

and see the three files I exported from my_project **and** two other files I exported from other projects. Setting project does not seem to have the desired effect.

## Additional detail
Files were exported using

```
# Loop through selected files, start one job for each.
exports = []
for f in my_files:
    export = api.exports.submit_export(
        file=f,                        
        volume=my_volume,                     
        location=f.name)
    
    exports.append(export)

    print("File {} is {} for export to your cloud storage \n"
          .format(f.name,exports[-1].state))
```

**Comment by jackDiGi** [comment]
This contrasts with 
```
import_job = api.imports.submit_import(volume=my_volume,
                                           project=my_project,
                                           location=f_name)
```
which **does restrict** results only to imports to my_project exactly as expected.

**Comment by SenadI** [comment]
@jackDiGi  - It seams that I've made an error here Jack. Exports can not be queried by project like imports do. I will close this issue once I remove the project attribute from the submit_export method.
