### ISSUE TITLE
Api __repr__ passed during task input copying

### ISSUE THREAD

**Issue by marouf-github** [sbg/sevenbridges-python#3]
When copying task inputs from another task the api __repr__ somehow ends up in the inputs object. When the inputs are saved next time wrapper will throw Json Not Serializable Exception

**Comment by SenadI** [comment]
I can confirm this. Will be fixed in the next release.  Will update you with the release version.
Thank you for this bug report, nice catch.

**Comment by SenadI** [comment]
@marouf-github ... Fixed in version 0.2.0
