### ISSUE TITLE
.rsplit() in create_app_revision() not raising IndexError

### ISSUE THREAD

**Issue by jackDiGi** [sbg/sevenbridges-python#36]
[via @jdagilliland, @ysaletore]

If a user passes in an id like
`id = name/project/app_id/revision`
then this method works. But since the method is also passed revision, this seems _redundant_ - so the user might try instead
`id = name/project/app_id`

Now the app_id will be split off (instead of the revision) and there seems to be no check that it was a string. In the project, the user will have an app called
`name/project/revision/0`
where revision was passed into create_app_revision()

**Comment by SenadI** [comment]
Hi @jackDiGi thank you for the input, I will look into it as soon as I have a chance. Once again thank you for the report.

**Comment by SenadI** [comment]
@jackDiGi This issue was fixed by merging @jdagilliland pull request.
