### ISSUE TITLE
API rate limits

### ISSUE THREAD

**Issue by mattions** [sbg/sevenbridges-python#45]
I was trying to get the limits for my user on the API, but I get None for all the three calls:

```
import sevenbridges as sbg
c = sbg.Config(profile='sbpla')
api = sbg.Api(config=c)
# Let's print the rate limit:
print(api.limit) # prints None
print(api.remaining) # prints None
print(api.reset_time) # prints None
```

However, if I do call my user first I get the expected result:
```
api.users.me()
print(api.limit)
print(api.remaining)
print(api.reset_time)
```

Output
````
<User: username=mmattioni>
1000
999
2016-10-05 15:34:54
```

I guess this is a minor bug, or if it is intended to be used like this, the docs should be updated:  http://sevenbridges-python.readthedocs.io/en/latest/quickstart/#rate-limit

I guess it's @SenadI and @damirkrstanovic call

**Comment by mattions** [comment]
More on this.

check this function:

```
def check_api_limits(call_user=True):
    if call_user:
        api.users.me()
    print("The limit is: {0}, the number of remaining call is: {1}, will be reset at: {2}".format(
        api.limit, api.remaining, api.reset_time))
```

If I call the user I get:
```
check_api_limits(call_user=True)
The limit is: 1000, the number of remaining call is: 981, will be reset at: 2016-10-05 15:41:06
```
otherwise I do get no update:
```
check_api_limits(call_user=False)
The limit is: 1000, the number of remaining call is: 981, will be reset at: 2016-10-05 15:41:06
```

**Comment by SenadI** [comment]
Rate limit becomes available when you call something on the API. Prior to that you can not get your rate limit because there is None set. This is a correct behaviour. I agree that additional documentation should be added to state this fact more precisely and I will add it.

**Comment by mattions** [comment]
@SenadI yeah that makes sense. Just add it to the docs so a user knows :+1:

**Comment by delicb** [comment]
@SenadI Maybe we can fetch rate limit info if they are set to None? That way, if user did send some requests, rate limit will be populated and we can just return it, but if rate limit check is first thing that user checks - we can fetch it, populate it and return it? Does that make sense to you?

**Comment by SenadI** [comment]
@delicb, @mattions -  Considering that there are already two supporters for this I yield :) Will be done in the next version. The rate limit will be fetched if it evaluates to None
