### ISSUE TITLE
Minor bug in authentication with environmental variables due to proxies

### ISSUE THREAD

**Issue by sethi7ik** [sbg/sevenbridges-python#46]
Cannot authenticate with OS environmental variables:

os.environ['API_URL'] = 'https://cgc-api.sbgenomics.com/v2'
os.environ['AUTH_TOKEN'] = authToken
api_config = sbg.Config()
api = sbg.Api(config=api_config)

-------
gives:
proxies = config.proxies
AttributeError: 'Config' object has no attribute 'proxies'

Looking at source code in config.py -> 

            self.auth_token = os.environ.get('AUTH_TOKEN')
            self.oauth_token = os.environ.get('OAUTH_TOKEN')
            self.api_url = os.environ.get('API_URL')
            if not self.auth_token and not self.oauth_token:
                raise SbgError(
                    'auth-token or oauth-token environment variable missing.'
                )
            if not self.api_url:
                raise SbgError('api-url variable environment missing.')

self.proxies is never initialized in __init__ function.

**Comment by SenadI** [comment]
@sethi7ik Just confirmed this one. Expect the bug fix soon.
