### ISSUE TITLE
Fetch only tasks newer than a given date

### ISSUE THREAD

**Issue by bjoernpollex** [sbg/sevenbridges-python#49]
Currently the only way to get tasks newer than a given date is to fetch all tasks and then filter. This is impractical for projects that contain large numbers of tasks. It would be great to either have direct support for this, or the option to iterate over the collection of tasks sorted by decreasing start-time.

**Comment by SenadI** [comment]
@bjoernpollex We will try to add this support on server first because we are lacking it there, when this happens we will be able to add the support to the library.

**Comment by SenadI** [comment]
@bjoernpollex We added support for this in 0.7.0 :) Closing the issue
