### ISSUE TITLE
Project description with quotes have issues on API

### ISSUE THREAD

**Issue by sethi7ik** [sbg/sevenbridges-python#50]
Noticed that the API throws an error when there are single quotes within the project description,

Code:
project_name = 'Copy of Cancer Cell Line Encyclopedia (CCLE)'
my_project = [p for p in api.projects.query(limit=100).all() \
              if p.name == project_name][0]
print('Project description: {} \n'.format(my_project.description))

Error:
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-7-65c0cd7d52b6> in <module>()
---> 4         print('Project description: {} \n'.format(my_project.description))

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 2299: ordinal not in range(128)

**Comment by SenadI** [comment]
Hi @sethi7ik,

Were you using python2.7 ? Its bug for sure but it will help me narrow it down. I bet I called `str` on a unicode object somewhere or something of sort. Will have to check it out. In any case thank you for catching this one.

**Comment by sethi7ik** [comment]
Yes @SenadI, my jupyter-notebooks are set up with python2.7

**Comment by SenadI** [comment]
@sethi7ik 
I just checked this. Library did parse and return the proper data the problem is in using the format function which detects weird unicode characters. 

```
'{}'.format(p.description.encode('ascii', 'ignore'))
```
