### ISSUE TITLE
Upload of an empty file fails

### ISSUE THREAD

**Issue by bosonogi** [sbg/sevenbridges-python#56]
There is a zero division error when calculating progress; but even with that taken care of, there is some issue with multi-part-uploading an empty file.

This old discussion might be of use: https://github.com/kr/s3/issues/30

**Comment by SenadI** [comment]
Hi @bosonogi Thanks for heads-up on the client side we will fix it for the next version for s3 related discussion I will have to check it out and get back to you later.

**Comment by SenadI** [comment]
@bosonogi 
We will completely forbid uploading of files with size = 0.

**Comment by SenadI** [comment]
Fixed in 0.7.0

**Comment by christiansbg** [comment]
Yes, we have this on the backlog now and we will allow uploading of empty files, although I can't give a timeline just yet.
