### ISSUE TITLE
Some log messages emited from root logger

### ISSUE THREAD

**Issue by bjoernpollex** [sbg/sevenbridges-python#67]
The module emits some log-message using the root-logger. For example, when creating an API object:

```python
from sevenbridges import Api, Config

Api(config=Config(profile='igor'))
```

These messages are emited from the root logger:

> No proxy configuration present. Skipping...
> Client settings: [url=***] [token=https://api.sbgenomics.com/v2] [proxy={'https': None, 'http': None}]

Also, in this message, `url` and `token` are swapped.

It would be more intuitive if all messages from this library are under `sevenbridges`, this makes filtering much easier.

**Comment by SenadI** [comment]
Hi @bjoernpollex as always nice catch, and thank you for noticing this. We will fix it in the next minor version.

**Comment by SenadI** [comment]
Fixed.
