### ISSUE TITLE
Discrepency in README.1st for credentials

### ISSUE THREAD

**Issue by golharam** [sbg/sevenbridges-python#72]
The readme.1st states "Use the configuration file $HOME/.sbgrc with defined parameters.", however below there is reference to "$HOME/.sevenbridges/credentials".

Which is correct?

**Comment by golharam** [comment]
In addition, in config.py, the Profile class refers to $HOME/.sevenbridges/credentials.   So I think the reference to .sbgrc is incorrect.

class Profile(object):
    CREDENTIALS = os.path.join(os.path.expanduser('~'), '.sevenbridges',
                               'credentials')
    PROXIES = os.path.join(os.path.expanduser('~'), '.sevenbridges',
                           'sevenbridges-python', 'config')

**Comment by jdagilliland** [comment]
That's correct, I noticed the change the other day when I resurrected an old script. `~/.sbgrc` no longer works with the library, but `~/.sevenbridges/credentials` does.

**Comment by delicb** [comment]
@golharam @jdagilliland You are both right. 
This change was introduced with version `0.7.0`, [released](https://github.com/sbg/sevenbridges-python/blob/develop/CHANGES.md#070-2016-02-10) on February 2nd.

@golharam You are right about documentation bug. We will make sure to iron it out. Sorry for the confusion.

**Comment by SenadI** [comment]
Resolved in 0.7.4
