### ISSUE TITLE
api.files.query(project, name=[]) returns all files, not none as expected

### ISSUE THREAD

**Issue by kghosesbg** [sbg/sevenbridges-python#81]
I expect the call
```
api.files.query(project, names=[])
```
To return no files because the file name list can be generated programmatically, and an empty list would mean no files need be fetched.

I would expect
```
api.files.query(project, names=None)
```
to return all files as that is equivalent to an omitted parameter, which asks the API to fetch all files

However, both queries return all files in project. Thanks! -Kaushik

**Comment by SenadI** [comment]
Fixed in 0.8.0
