### ISSUE TITLE
Issue with download

### ISSUE THREAD

**Issue by SenadI** [sbg/sevenbridges-python#82]
Amazon error under specific circumstances ends up in the file. I need to parse xml to validate errors.

**Comment by raunaqsbg** [comment]
An example of this is the following:
A file contains the following content: 
```
ColumnA ColumnB ColumnC
1 2 3.00
```

But when downloading it, the following lines are added inside the file itself: 

`
rror</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>ABVFASDFRDFG</RequestId><HostId>SomeHostID</HostId></Error>
`

**Comment by SenadI** [comment]
Fixed in 0.8.0
