### ISSUE TITLE
Copying a task inputs or outputs returns a dict and converts file objects to dicts

### ISSUE THREAD

**Issue by jsspencer** [sbg/sevenbridges-python#84]
Similar to #70, doing

`task.inputs.copy()`

returns a `dict` rather than `sevenbridges.models.compound.tasks.input.Input` (which is fine) and converts all objects which were `sevenbridges.models.file.File` to `dict` objects (less fine). The same issue affects task outputs.

**Comment by SenadI** [comment]
Fixed in 0.8.0
