### ISSUE TITLE
Make iterating over all entries default

### ISSUE THREAD

**Issue by Gig77** [sbg/sevenbridges-python#87]
Current API behavior is to return only the first page of results (defaults to first 50 entries) when querying a set, for examples files or tasks.

```
# iterates only over first 50 files in project
for f in api.files.query(project="myprojecid"):
    print(f.name)
```

If one wants to iterate over all result entries, the `.all()` notation must be used:

```
# iterates over all files in project
for f in api.files.query(project="myprojecid").all():
    print(f.name)
```

I would say this is currently _the_ most overlooked issue for API novices. Personally, this bit me several times when I started using the API, with typically 20+ minutes debugging time because the problem does not manifest itself in any output or error log. I have also seen several other users struggling with this when they got to learn the API. In addition, this error typically shows after deployment, because developers tend to work on small sets < 50 entries. 

I know there are very good technical reasons for this behavior. But if pagination could somehow happen silently in the background without the user noticing, that would be preferred.

**Comment by SenadI** [comment]
@Gig77 I understand this input but we will not enable this behaviour. The pagination follows the server quite well and library is easy-to-use and well documented.
