### ISSUE TITLE
typo in quickstart

### ISSUE THREAD

**Issue by jackDiGi** [sbg/sevenbridges-python#9]
Missing comma before 'run' [here](http://sevenbridges-python.readthedocs.io/en/latest/quickstart/#managing-tasks): 

try:
    task = api.tasks.create(name=name, project=project, app=app,
                            inputs=inputs, batch_input=batch_input, batch_by=batch_by run=True)

**Comment by SenadI** [comment]
Will be fixed in milestone 0.4.0.
Thank you jack for reporting this.

**Comment by SenadI** [comment]
Resolved in the latest 0.4.0 version
