### ISSUE TITLE
Harmonising the unit of duration fields

### ISSUE THREAD

**Issue by asyavuz** [sbg/sevenbridges-python#93]
Hi,

Duration fields returned by API (as in task execution details) is apparently in milliseconds scale, while python bindings report upload/download durations in seconds. Is it possible to harmonise these time scales without possibly breaking any API scripts developed over time?

Best,

**Comment by SenadI** [comment]
@asyavuz We can change that upload/download also report duration in milliseconds. I am not aware of any scripts that are dependent on these values, but many do depend on ms values on resource models like Task and similar. 

I agree with you we should harmonise this and the best thing we can do is bump a major version for this update and signal potential breaking changes.

**Comment by SenadI** [comment]
Resolved in 0.9.0
