### ISSUE TITLE
Filemodification times contain no timezone information

### ISSUE THREAD

**Issue by bjoernpollex** [sbg/sevenbridges-python#95]
The attributes `created_on` and `modified_on` of `sevenbridges.models.file.File` don't have associated timezone information (and `f.modified_on.tzinfo is None` is `True`), and they are not UTC timestamps either.

Specifically, given a file `f` on the platform, the following is not true:

```python
f.modified_on == datetime.fromtimestamp(timegm(f.modified_on.timetuple()))
```

In my case the difference is exactly one hour. Ideally these timestamps would always be UTC, but if they are not, they should at least have timezone information.

**Comment by SenadI** [comment]
Hi @bjoernpollex `.fromtimestamp` returns local date and time. As you can see now the date is correct.

```python
In [22]: datetime.fromtimestamp(timegm(f.modified_on.timetuple()), pytz.UTC)
Out[22]: datetime.datetime(2017, 9, 20, 8, 2, 43, tzinfo=<UTC>)

In [23]: f.modified_on
Out[23]: datetime.datetime(2017, 9, 20, 8, 2, 43)
```

**Comment by bjoernpollex** [comment]
Ha, timezones! - I should have expected that I'd screw this up. Thanks for the clarification!
